# Add two variables

In [7]:
x=float(input('Enter first no:'))
y=float(input('Enter second no:'))
Sum=x+y
print('sum of two variables is',Sum)

Enter first no:675655
Enter second no:34535
sum of two variables is 710190.0


# Multiply two variables

In [8]:
x=float(input('Enter first no:'))
y=float(input('Enter second no:'))
product=x*y
print('Product of two variables is',product)

Enter first no:543444
Enter second no:34344
Product of two variables is 18664040736.0


# Area of Triangle

In [9]:
x=int(input('Base of triangle:'))
y=int(input('Height of triangle:'))
Area=1/2*x*y
print('Area of Triangle is',Area)

Base of triangle:34343444
Height of triangle:3432433
Area of Triangle is 58940785259626.0


# Swap two variable using 3rd variable

In [12]:
x=32
y=8
temp=x
x=y
y=temp
print('value of x now {} and value of y {}'.format(x,y))

value of x now 8 and value of y 32


# Swap two variable without using 3rd variable

In [13]:
x=32
y=8
x,y=y,x
print('value of x now {} and value of y {}'.format(x,y))

value of x now 8 and value of y 32


# Convert KM to Miles

In [14]:
KM=int(input('Enter your no in KM:'))
Miles=0.625*KM
print(KM,'km in miles is equal to',Miles,'miles')

Enter your no in KM:65
65 km in miles is equal to 40.625 miles


# Convert celcius to Fahrenheit

In [15]:
celcius=float(input('Enter your no in celcius:'))
F=(celcius*9/5)+32
print(celcius,'degree celcius in Fahrenheit is equal to',F,'F')

Enter your no in celcius:67.9
67.9 degree celcius in Fahrenheit is equal to 154.22 F


# Is a no. +ve , -ve , or 0

In [19]:
num=float(input('Enter your no:'))
if num<0:
    print('It is -ve no.')
elif num>0:
    print('It is +ve no.')
else:
    print('It is 0')

Enter your no:-0.4
It is -ve no.


# Check Even or Odd number

In [20]:
Num=int(input('Enter your no:'))
if Num%2==0:
    print('It is Even number')
else:
    print('It id Odd number')

Enter your no:876
It is Even number


# To check a Leap Year

In [22]:
year=int(input('Enter your year:'))
if year%4==0 and year%100!=0:
    print('It is a Leap year')
elif year%400==0 and year%100==0:
    print('It is a Leap year')
else:
    print('It is not a Leap year')

Enter your year:1700
It is not a Leap year


# Find the largest Number

In [23]:
Num1=float(input('Enter the 1st no:'))
Num2=float(input('Enter the 2nd no:'))
Num3=float(input('Enter the 3rd no:'))
if (Num1>Num2) and (Num1>Num3):
    print('Num1 is the largest number')
elif (Num2>Num1) and (Num2>Num3):
    print('Num2 is the largest number')
else:
    print('Num3 is the largest number')

Enter the 1st no:64554.85674
Enter the 2nd no:64554.85673
Enter the 3rd no:64554.856741
Num3 is the largest number


# To check the Prime Number

In [27]:
x=int(input('Enter your no:'))
if x<=1:
    print('Not a prime no')
if x>=1:
    for i in range(2,x):
        if x%i==0:
            print('Not a prime no')
            break
    else:
        print('It is a Prime no')

Enter your no:453
Not a prime no


# Print all Prime no. in a interval

In [8]:
lower_limit = int(input('Enter the lower limit'))
upper_limit = int(input('Enter the upper limit'))
for any_num in range(lower_limit,upper_limit+1):
    if any_num>1:
        for i in range(2,any_num):
            if  any_num%2==0:
                break
        else:
            print(any_num)

Enter the lower limit10
Enter the upper limit17
11
13
15
17


# Display Power of n using Anonymous Function

In [17]:
n=int(input('enter that no whose anonymous function you want'))
nterms=int(input('enter no of terms here'))
lst=list(map(lambda nterms : n**nterms,range(nterms+1)))
print(lst)

enter that no whose anonymous function you want3
enter no of terms here5
[1, 3, 9, 27, 81, 243]


# Find numbers which are divisible by a Particular number

In [30]:
n=int(input('Enter that no. whose divisible no. you want:'))
for i in range(1,100):
    if i%n==0:
        print(i)

Enter that no. whose divisible no. you want:15
15
30
45
60
75
90


# Find numbers which are divisible by a Particular number using Anonymous Function

In [27]:
lower=int(input('Enter the lower limit no:'))
upper=int(input('Enter the upper limit no:'))
n=int(input('Enter that no whose divisible no you want:'))
for num in range(lower,upper+1):
    lst=list(filter(lambda num : num%n==0 ,range(lower,upper+1)))
print(lst)

Enter the lower limit no:45
Enter the upper limit no:288
Enter that no whose divisible no you want:14
[56, 70, 84, 98, 112, 126, 140, 154, 168, 182, 196, 210, 224, 238, 252, 266, 280]


# Factorial of a Number using Recursion

In [3]:
def fact(a):
    if a==0:
        return 1
    elif a<0:
        print('No result for -ve no')
    else:
        return a*fact(a-1)
a=int(input('Enter a no:'))
result=fact(a)
print('Factorial of your no is',result)
        

Enter a no:8
Factorial of your no is 40320


# Factorial of a Number using For Loop

In [7]:
n=int(input('Enter a no:'))
fact=1
if n==0:
    print('factorial of 0 is',1)
elif n<0:
    print('Enter a +ve no')
else:
    for i in range(1,n+1):
        fact=fact*i
    print('Factorial of your no is',fact)

Enter a no:8
Factorial of your no is 40320


# Multiplication Table using For Loop

In [8]:
n=int(input('Enter that no whose table you want:'))

for i in range(1,11):
    table=n*i
    print(table)

Enter that no whose table you want:2
2
4
6
8
10
12
14
16
18
20


# Multiplication Table using While Loop

In [9]:
n=int(input('Enter that no whose table you want:'))
i=1
while i<=10:
    table=n*i
    i=i+1
    print(table)

Enter that no whose table you want:2
2
4
6
8
10
12
14
16
18
20


# Print Fibonacci Sequence

In [16]:
a=0
b=1
term=int(input('Enter the no of terms of fibonacci seq :'))
if term==1:
    print(a)
else:
    print(a)
    print(b)
    for i in range(2,term):
        c=a+b
        a=b
        b=c
        print(c)

Enter the no of terms of fibonacci seq :7
0
1
1
2
3
5
8


# Sum of Natural Number

In [23]:
n=int(input('Enter your natural no:'))
Sum=0
while n>0:
    Sum=Sum+n
    n=n-1
print(Sum)

Enter your natural no:5
15


# Convert decimal no into Octal,Binary,Hexadecimal number

In [32]:
decimal=int(input('Enter a decimal no:'))
print(bin(decimal),'is the binary no of',decimal)
print(oct(decimal),'is the octal no of',decimal)
print(hex(decimal),'is the hexadecimal no of',decimal)

Enter a decimal no:5
0b101 is the binary no of 5
0o5 is the octal no of 5
0x5 is the hexadecimal no of 5


# Find ASCII value of characters

In [59]:
char=str(input('Enter any character:'))
print(ord(char),'is the ASCII value of',char)

Enter any character:y
121 is the ASCII value of y


# Find HCF\GCD of two numbers

In [69]:
x=int(input('Enter 1st number:'))
y=int(input('Enter 2nd number:'))
def findhcf(x,y):
    if x>y:
        samller=y
    else:
        smaller=x
        for i in range(1,smaller+1):
            if ((x%i==0) and (y%i==0)):
                hcf=i
        return hcf
findhcf(x,y)
            
        

Enter 1st number:15
Enter 2nd number:35


5

# Simple Calculator

In [54]:
x=float(input('enter 1st no:'))
y=float(input('enter 2nd no:'))
print('Press 1 for ADDITION\nPress 2 for SUBTRACTION\nPress 3 for MULTIPLICATION\nPress 4 for DIVISION')
choice=int(input('Enter no between 1-4'))
if choice==1:
    print(x+y)
elif choice==2:
    print(x-y)
elif choice==3:
    print(x*y)
elif choice==4:
    print(x/y)
else:
    print('Enter a valid number')
    

enter 1st no:5
enter 2nd no:5
Press 1 for ADDITION
Press 2 for SUBTRACTION
Press 3 for MULTIPLICATION
Press 4 for DIVISION
Enter no between 1-44
1.0


# Find the Factors of a Number

In [56]:
n=int(input("Enter that no whose factors you want:"))
for i in range(1,n+1):
    if n%i==0:
        print(i)

Enter that no whose factors you want:34
1
2
17
34


# Shuffle Deck of Cards

In [28]:
import random,itertools
deck=list(itertools.product(range(1,14),['spade','club','heart','diamond']))
random.shuffle(deck)
print(deck)


print('First 5 shuffle cards are:-')
for i in range(5):
    print(deck[i])

[(8, 'spade'), (2, 'diamond'), (6, 'club'), (4, 'heart'), (3, 'spade'), (9, 'spade'), (11, 'club'), (3, 'diamond'), (9, 'heart'), (7, 'heart'), (5, 'diamond'), (8, 'diamond'), (13, 'club'), (6, 'heart'), (9, 'club'), (12, 'heart'), (4, 'spade'), (5, 'club'), (1, 'diamond'), (7, 'spade'), (10, 'heart'), (6, 'diamond'), (4, 'club'), (8, 'club'), (3, 'club'), (12, 'club'), (2, 'heart'), (2, 'spade'), (12, 'spade'), (1, 'spade'), (11, 'diamond'), (10, 'spade'), (7, 'club'), (5, 'spade'), (2, 'club'), (7, 'diamond'), (4, 'diamond'), (10, 'diamond'), (12, 'diamond'), (3, 'heart'), (13, 'spade'), (9, 'diamond'), (13, 'diamond'), (10, 'club'), (8, 'heart'), (6, 'spade'), (1, 'heart'), (1, 'club'), (5, 'heart'), (11, 'heart'), (13, 'heart'), (11, 'spade')]
First 5 shuffle cards are:-
(8, 'spade')
(2, 'diamond')
(6, 'club')
(4, 'heart')
(3, 'spade')


# Display Calender

In [34]:
import calendar
year=int(input('Enter the year:'))
month=int(input('Enter the month:'))
c=calendar.month(year,month)
print(c)


Enter the year:1998
Enter the month:7
     July 1998
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



# Fibonacci Series using Recursion

In [35]:
def febo(n):
    if n<=1:
        return n
    else:
        return febo(n-1)+febo(n-2)
n=int(input('jitne no tak ki series chahea vo no likho:'))
if n<=0:
    print('Enter a positive no')
else:
    for i in range(n):
        print(febo(i))

jitne no tak ki series chahea vo no likho:5
0
1
1
2
3


# Sum of Natural number Using Recursion

In [39]:
def snn(n):
    if n<=0:
        print('Enter natural no only')
    elif n==1:
        return n
    else:
        return n+snn(n-1)
n=int(input('jitne no tak sum chea vo no likho:'))
print(snn(n))

jitne no tak sum chea vo no likho:5
15


# Factorial using Recursion

In [41]:
def fact(n):
    if n<0:
        print('Enter positive no only')
    elif n==0:
            return 1
    elif n==1:
            return 1
    else:
        return n*fact(n-1)
n=int(input('jis no ka factorial chea vo no likho:'))
print(fact(n))
        

jis no ka factorial chea vo no likho:5
120


# Convert Decimal to Binary using Recursion

In [57]:
def bina(n):
    if n>1:
        bina(n//2)
    print(n%2)
n=int(input('Enter the decimal no:'))
print(bina(n))

Enter the decimal no:5
1
0
1
None


# Add two Matrices

In [69]:
import numpy as np
A=np.arange(1,10).reshape(3,3)
print(A)
B=np.arange(11,20).reshape(3,3)
print(B)
R=np.zeros((3,3))
print(R)
for i in range(len(A)):
    for j in range(len(A[0])):
        R[i][j]=A[i][j]+B[i][j]
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[12. 14. 16.]
 [18. 20. 22.]
 [24. 26. 28.]]


# Transpose of Matrice Using For Loop

In [70]:
A=np.arange(1,10).reshape(3,3)
print(A)
T=np.zeros((3,3))
print(T)
for i in range(len(A)):
    for j in range(len(A[0])):
        T[i][j]=A[j][i]
print(T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


# Transpose of Matrics using List Comprihension

In [78]:
A=np.arange(1,10).reshape(3,3)
print(A)
T=[[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

for t in T:
    print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


# String is Palindrome or Not

In [80]:
char=input('Enter any word here:')
reverse_slicing=char[::-1]
if char==reverse_slicing:
    print('yes it is Palindrome')
else:
    print('Not a Palindrome')

Enter any word here:sachin
Not a Palindrome


# Remove the Punctuation from the String

In [84]:
punc="~`!@#$%^&*()_=[]{}|\:;''""?><.,/"
char=input('Enter anything with punctuation:')
filtered_str=''
for i in char:
    if i not in punc:
        filtered_str=filtered_str+i
print(filtered_str)
        
        

Enter anything with punctuation:hiiii am Dinehs.....
hiiii am Dinehs


# illustrate the  Different SETS of operations  Like:-   Union, Intersection, Difference,Symmetric Difference

In [85]:
A={1,2,3,4}
B={3,2,5,7}
print("Union of A and B is",A|B)
print("Intersection of A and B is",A&B)
print("Difference of A and B is",A-B)
print("Symmetric Difference of A and B is",A^B)

Union of A and B is {1, 2, 3, 4, 5, 7}
Intersection of A and B is {2, 3}
Difference of A and B is {1, 4}
Symmetric Difference of A and B is {1, 4, 5, 7}


# Count the no of VOWELS

In [109]:
v='aeiou'
char=input('Enter anything here')
char=char.casefold()
dic={}.fromkeys(v,0)
print(dic)
for i in char:
    if i in dic:
        dic[i]=dic[i]+1
print(dic)

Enter anything herejai sheya Ram
{'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
{'a': 3, 'e': 1, 'i': 1, 'o': 0, 'u': 0}


# Sort the Words in Alphabatic Order

In [114]:
a=input('Enter anything here:')
a=a.casefold()
s=a.split()
print(s)
s.sort()
print(s)
    

Enter anything here:Dinesh And sachin are eating food
['dinesh', 'and', 'sachin', 'are', 'eating', 'food']
['and', 'are', 'dinesh', 'eating', 'food', 'sachin']


# Product of two Matrices

In [119]:
A=np.arange(1,13).reshape(4,3)
print(A)
B=np.arange(11,20).reshape(3,3)
print(B)
R=np.zeros((4,3))
print(R)
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            R[i][j]=R[i][j]+A[i][k]*B[k][j]
print(R)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 90.  96. 102.]
 [216. 231. 246.]
 [342. 366. 390.]
 [468. 501. 534.]]


# Merging Two Dictionaries

In [1]:
#Using Bar operator
a={'Ram':100,'sita':101}
b={'Krishan':100,'Sita':102,'Radha':102}
print(a|b)

{'Ram': 100, 'sita': 101, 'Krishan': 100, 'Sita': 102, 'Radha': 102}


In [3]:
#Using Quacks Operator
a={'Ram':100,'sita':101}
b={'Krishan':100,'Sita':102,'Radha':102}
print({**a,**b})

{'Ram': 100, 'sita': 101, 'Krishan': 100, 'Sita': 102, 'Radha': 102}


In [5]:
#Using Copy and Update
a={'Ram':100,'sita':101}
b={'Krishan':100,'Sita':102,'Radha':102}
l=a.copy()
l.update(b)
print(l)


{'Ram': 100, 'sita': 101, 'Krishan': 100, 'Sita': 102, 'Radha': 102}


In [1]:
x=["ramlu","plum","dinesh"]
y="dinesh"
for l in x:
    if len(y)>len(l):
        y=l
print(y)
 
k=0
allmatch=True
l=""
for i in y:
    if allmatch:
        l=l+i
    else:
        print("there is no match")
    for j in range(len(x)):
        if i!=x[j][k]:
            k=k+1
            allmatch=False
            break
print(l)

plum
there is no match
there is no match
there is no match
p


In [3]:
def jood(lst):
    target=18
    lengthoflist=len(lst)
    for i in range(lengthoflist):
        for j in range(i,lengthoflist):
            if lst[i]+lst[j] == target:
                print([i,j])
lst=[2,7,11,15]
print(jood(lst))

[1, 2]
None


In [4]:
lst=[12,5,11,18]
target=16
lengthoflist=len(lst)
for i in range(lengthoflist):
    for j in range(i,lengthoflist):
        if lst[i]+lst[j] == target:
            print([i,j])

[1, 2]


In [19]:
a=[1,2,3,4,5]
a.reverse()
a

[5, 4, 3, 2, 1]

In [2]:
sq=lambda n:n**2
mod=lambda func:lambda num:func(num)+num
var=mod(sq)
print(var(int(input('Enter a number '))))

Enter a number 6
42


In [8]:
def bonus():
    bon=2000
    return bon
def total(bonus):
    slary=4000
    total=bonus+slary
    
    print(total)

In [9]:
def bonus():
    bon=2000
    return bon
def total(b):
    slary=4000
    total=b()+slary
    
    print(total)
total(bonus)

6000
